name: Release Client

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read app version
        id: read_version
        run: |
          cd client
          echo "VERSION=$(cat .app_version)" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false

  build_and_upload:
    runs-on: ubuntu-latest
    needs: create_release

    strategy:
      matrix:
        platform: [linux, darwin]
        architecture: [amd64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.22.1"

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: |
          cd client
          make build

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: dist/kecy-${{ matrix.platform }}-${{ matrix.architecture }}
          asset_name: kecy-${{ matrix.platform }}-${{ matrix.architecture }}
          asset_content_type: application/octet-stream
